//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookMovement()
        {
            this.BookMovementStatuses = new HashSet<BookMovementStatus>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int BookId { get; set; }
        public int BookMovement1 { get; set; }
        public int BookCount { get; set; }
        public System.DateTime DateMovement { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookMovementStatus> BookMovementStatuses { get; set; }
        public virtual Status Status { get; set; }
    }
}
