//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMovementStatus
    {
        public int Id { get; set; }
        public int BookMovementId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public bool Actual { get; set; }
    
        public virtual BookMovement BookMovement { get; set; }
        public virtual Status Status { get; set; }
    }
}
